before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - sudo apt-get update
install:
  - sudo apt-get install rust-nightly
script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=/tmp
  - make -j
  - make test -j
  - make doc -j
  - make install
